CREATE CURSOR MAXIMOS (IDVEHICULO C(10),DESCRIP C(40),CANTIDAD N(10,2))
SELECT IDVEHICULO FROM CVEHICULOS INTO ARRAY LAVEHICULOS 
IF !VARTYPE(LAVEHICULOS )="U"
	FOR N=1 TO ALEN(LAVEHICULOS,1 )
		LCVEH=LAVEHICULOS(N)

			INSERT INTO MAXIMOS (IDVEHICULO,DESCRIP ,CANTIDAD ) ;
				SELECT TOP 1 ;
					CVALES.IDVEHICULO ,CVEHICULOS.DESCRIP, MAX(CVALES_DET.cantidad)  ;
				FROM ;
					CVALES INNER JOIN CVALES_DET ON CVALES.IDVALE=CVALES_DET.IDVALE INNER JOIN CVEHICULOS ON CVALES.idvehiculo=CVEHICULOS.IDVEHICULO  ;
				WHERE ;
					ALLTRIM(CVALES.IDVEHICULO)=ALLTRIM(LCVEH) GROUP BY 1,2 ORDER BY 3 DESC

	ENDFOR 
ENDIF 

