&&Equipos x Fecha 
SELECT ;
	MPROGRA.FECHA AS FECHA ,;
	1/IIF(COUNT(MPROGRA.IDEQUIPO)<4,4,COUNT(MPROGRA.IDEQUIPO)) AS EQSXDIA;
FROM ;
	MPROGRA;
GROUP BY ;
	1;
INTO CURSOR;
	EQSXDIA 

&&Equipos programados en mprogra 
SELECT ;
	MPROGRA.IDPROGRA		AS IDPROGRA,;
	MCONTRATO_EQ.IDSUCURSAL	AS IDSUCURSAL,;
	MSUCURSAL.IDRUTA		AS IDRUTA,;
	MRUTAS.DESCRIP			AS RUTA,;
	MSUCURSAL.DESCRIP		AS SUCURSAL,;
	MPROGRA.IDEQUIPO		AS IDEQUIPO,;
	MPROGRA.IDGRUPO			AS IDGRUPO,;
	MPROGRA.FECHA			AS FECHA,;
	MPROGRA.SECUENCIA		AS SECUENCIA,;
	MPROGRA.DIASUGERIDO		AS DIASUGERIDO,;
	MPROGRA.PRECIO			AS PRECIO,;
	MPROGRA.ESTADO			AS ESTADO,;
	MPROGRA.OBS				AS OBS,;
	EQSXDIA.EQSXDIA 		AS EQSXDIA ;
FROM;
	MPROGRA INNER JOIN MCONTRATO_EQ ON MPROGRA.IDEQUIPO=MCONTRATO_EQ.IDEQUIPO ;
	INNER JOIN MSUCURSAL ON MCONTRATO_EQ.IDSUCURSAL=MSUCURSAL.IDSUCURSAL;
	INNER JOIN MRUTAS ON MSUCURSAL.IDRUTA=MRUTAS.IDRUTA;
	INNER JOIN EQSXDIA  ON MPROGRA.FECHA=EQSXDIA.FECHA  ;
ORDER BY ;
	4;
INTO CURSOR ;
	CAL_TMP

&&Resumen de calendario 
SELECT ;
	CAL_TMP.RUTA,;
	CAL_TMP.SUCURSAL,;
	COUNT(CAL_TMP.IDEQUIPO) AS EQUIPOS,;
	MIN(CAL_TMP.FECHA) AS FECHAI,;
	MAX(CAL_TMP.FECHA) AS FECHAF,;
	MAX(CAL_TMP.FECHA)-MIN(CAL_TMP.FECHA)+1 AS DIAS,;
	SUM(EQSXDIA.EQSXDIA ) AS EQSXDIA ;
FROM ;
	CAL_TMP INNER JOIN EQSXDIA ON CAL_TMP.FECHA=EQSXDIA.FECHA;
GROUP BY;
	1,2;
ORDER BY ;
	4;
INTO CURSOR ;
	CAL_TMP2







