PROCEDURE GENCURVAL3
LPARAMETERS lbRecrear,lcTpDoc
	&&algoritmo medular 
	IF !USED("EQ")
		DO EQ
	ELSE
		IF lbRecrear 
			DO REFEQ
		ENDIF
	ENDIF
	SELECT EQ 
ENDPROC 

PROCEDURE EQ
	&&Cursor EQ base Y UNICO PARA EQUIPOS 
	SELECT;
		EQUIPOS.IDEQUIPO,;
		EQUIPOS.SERIE ,;
		EQUIPOS.MODELO,;
		EQUIPOS.MARCA,;
		EQUIPOS.CAPACIDAD,;
		EQUIPOS.UBICACION,;
		EQUIPOS.OBSERVACIO;
	FROM ;
		EQUIPOS ;
	INTO CURSOR ;
		EQ READWRITE 
	SELECT EQ
	INDEX ON IDEQUIPO TAG IDEQUIPO
	INDEX ON SERIE TAG SERIE 
	INDEX ON MODELO TAG MODELO
	INDEX ON MARCA TAG MARCA 
	INDEX ON CAPACIDAD TAG CAPACIDAD 
	INDEX ON UBICACION TAG UBICACION 
	INDEX ON OBSERVACIO TAG OBSERVACIO
ENDPROC 




PROCEDURE REFEQ
	SELECT;
		EQUIPOS.IDEQUIPO,;
		EQUIPOS.SERIE ,;
		EQUIPOS.MODELO,;
		EQUIPOS.MARCA,;
		EQUIPOS.CAPACIDAD,;
		EQUIPOS.UBICACION,;
		EQUIPOS.OBSERVACIO;
	FROM ;
		EQUIPOS ;
	INTO CURSOR ;
		TEMPEQ 
	&&refilando el cursor EQ de  TempEQ
	SET SAFETY OFF
	ZAP IN EQ 
	SET SAFETY ON 
	SELECT EQ 
	APPEND FROM DBF('tempEQ' ) 
ENDPROC 


*Agregar SUCURSALES
PROCEDURE SUCURSALES
	SELECT ;
		DETALLEFACTURAS.idVenta AS IDPRESUP ,;
		FACTURAS.IDCLIENTE AS IDCLIENTE,;
		FACTURAS.DEPTO AS PROYECTO,;
		FACTURAS.DESCRIPCION AS DSC ,;
		SUM(PR.COSTO) AS COSTO,;
		SUM(PR.RETENCIONIVA) AS RETENCIONIVA,;
		SUM(PR.IVA) AS IVA,;
		SUM(PR.MONTO) AS MONTO;		
	FROM ;
		DETALLEFACTURAS INNER JOIN FACTURAS ON DETALLEFACTURAS.IDVENTA=FACTURAS.IDVENTA;
		LEFT JOIN PR ON DETALLEFACTURAS.REFERENCIA=PR.IDPRESUP;
	GROUP BY ;
		1,2,3,4;
	INTO CURSOR ;
		TEMPFACT
	SELECT TEMPFACT
	
	SELECT PR 
	APPEND FROM DBF('TEMPFACT')
ENDPROC 





PROCEDURE VerVars
	llVarType=VARTYPE(gRETIVA)="U" OR VARTYPE(gIVA)="U" OR VARTYPE(gRENTA)="U" OR VARTYPE(gRETIVA13)="U"
	IF llVarType
		DO CONFIGAPP 
	ENDIF 
ENDPROC