PARAMETERS lsCodigo,ldFecha
LOCAL lnAcum, lnPromedio,lnCantidad
IF EMPTY(lsCodigo)
	RETURN 0.00
	
ELSE 
	lnAcum=0
	lnPromedio=0
	lnCantidad=0

	SELECT ;
		SUM(CANTIDAD*COSTO);
	FROM;
		DETALLEORDEN INNER JOIN ORDENCOMPRA ON DETALLEORDEN.NORDEN=ORDENCOMPRA.NORDEN;
	WHERE;
		DETALLEORDEN.CODIGO=LSCODIGO AND ;
		ORDENCOMPRA.FECHA<=LDFECHA;
	INTO ARRAY;
		aSTotal
		
	aSTotal(1)=IIF(VARTYPE(aSTotal)="X",0.00,aSTotal(1))

	SELECT ;
		SUM(CANTIDAD);
	FROM;
		DETALLEORDEN INNER JOIN ORDENCOMPRA ON DETALLEORDEN.NORDEN=ORDENCOMPRA.NORDEN;
	WHERE;
		DETALLEORDEN.CODIGO=LSCODIGO AND ;
		ORDENCOMPRA.FECHA<=LDFECHA;
	INTO ARRAY;
		aSCant
	aSCant(1)=IIF(VARTYPE(aSCant)="X",0.00,aSCant(1))

	lnPromedio=ROUND(IIF(aSCant(1)=0,0.00,aSTotal(1)/aSCant(1)),4)
	RETURN lnPromedio
ENDIF 